In [1]:
import requests

In [2]:
website_url= requests.get('https://www.census.gov/foreign-trade/balance/c5700.html').text

In [3]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(website_url,'lxml')
print(soup.prettify())

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
 <!-- #BeginTemplate 'file://///sharedncs_ftd_server/ftd/FTD/SDSB/All FTD Staff
/IEWORK/internet/foreign-trade/Templates/DATA_3COL_Current.dwt' -->
 <!-- DW6 -->
 <head>
  <!--Each page must contain this info, per OMB, update info as neccessary-->
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <!-- #BeginEditable 'meta info' -->
  <meta content="Foreign Trade: Data" name="DC.title"/>
  <meta all="" and="" can="" content="The U.S. Census Bureau" data="" data.="" date="" every="" find="" foreign="" here.="" is="" latest="" month="" most="" name="DC.description" of="" program="" release="" s="" source="" the="" to="" trade="" u.s.="" up="" we="" you=""/>
  <meta content="imports, exports, trade, balance, China " name="DC.subject"/>
  <meta content="noodp" name="robots"/>
  <meta content="US Census Bureau Foreign Trade Division" name="DC.creator"/>
  <meta content="2009-04-21" name="DC.date.created" scheme="ISO8601"/>
  <meta content="2009-07-22" name="DC.date.reviewed" scheme="ISO8601"/>
  <meta content="EN-US" name="DC.language" scheme="DCTERMS.RFC1766"/>
  <meta content="Foreign Trade Data Dissemination Branch" name="author"/>
  <!-- #EndEditable -->
  <!-- #BeginEditable 'Page Title' -->
  <title>
   Foreign Trade - U.S. Trade with China
  </title>
  <!-- #EndEditable -->
  <!-- Site wide JS -->
  <script src="/main/javascript/ruthsarian_utilities.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   <!--
if ( ( typeof( set_min_width ) ).toLowerCase() != 'undefined' ) { set_min_width( 'page-container' , 853 ); }
if ( ( typeof( sfHover ) ).toLowerCase() != 'undefined' ) { event_attach( 'onload' , function () {
sfHover( 'middlemenu' );
} ); }
//-->
  </script>
  <script src="/main/javascript/unlink.js" type="text/javascript">
  </script>
  <script src="/main/javascript/jquery.js" type="text/javascript">
  </script>
  <!--End JavaScript Links-->
  <!-- CSS Styles -->
  <!-- #BeginEditable 'css' -->
  <!-- You can edit the path to the CSS.  CSS MUST stay in a folder called 'css' on the server-->
  <link href="/foreign-trade/css/SiteDefined.css" media="screen" rel="stylesheet" type="text/css"/>
  <link href="/foreign-trade/css/print.css" media="print" rel="stylesheet" type="text/css"/>
  <!-- #EndEditable -->
  <link href="/main/css/menus.css" media="all, handheld" rel="stylesheet" type="text/css"/>
 </head>
 <body>
  <div id="page-container">
   <noscript>
    This Javascript allows the page in IE to resize to the minimum width of 853 pixels and no less.
   </noscript>
   <!-- RESPONSIVE HEADER LAST UPDATED 7/12/2018 -->
   <button class="cb-header-skip-nav sr-only sr-only-focusable">
    Skip to main content
   </button>
   <header>
    <div id="top_innerPage">
     <!-- Used for CSS resets and making rendering consistent across all browsers/devices -->
     <!-- add Universal Federated Analytics -->
     <script class="global-file" id="_fed_an_ua_tag" language="javascript" src="/main/javascript/federated-analytics-min.js?agency=DOC&amp;subagency=CEN">
     </script>
     <!-- This code is for web metrics - SiteCatalyst -->
     <script class="global-file" src="//www.census.gov/main/javascript/s_code.js" type="text/javascript">
     </script>
     <script type="text/javascript">
      var s_code = s.t();
            if (s_code) document.write(s_code)
     </script>
     <!-- end of web metrics code -->
     <!-- Adding original census.gov css-->
     <link class="cb-main-support global-file" href="/main/css/_new/bootstrap.css" rel="stylesheet"/>
     <link class="cb-main-support global-file" href="/main/css/_new/base.css" rel="stylesheet"/>
     <link class="cb-main-support global-file" href="/main/css/_new/extra.css" rel="stylesheet"/>
     <link class="cb-main-support global-file" href="/main/css/_new/typeahead.css" rel="stylesheet"/>
     <link class="cb-main-support global-file" href="/main/css/_new/header.css" rel="stylesheet"/>
     <link class="cb-main-support global-file" href="/main/css/_new/search.css" rel="stylesheet"/>
     <script class="cb-main-support global-file" src="/main/responsive-header/jquery/jquery.js">
     </script>
     <script class="cb-main-support global-file" src="/main/responsive-header/jquery/jquery-ui.js">
     </script>
     <!-- Check for jquery conflict  -->
     <script type="text/javascript">
      $acn = jQuery.noConflict();
            if (typeof jQuery === 'undefined' || typeof $ === 'undefined') {
                jQuery = $acn;
                $ = $acn;
            }
            $(function () {
                $('.cb-header-skip-nav').click(function () {
                    $('#cb-after-header-anchor').focus();
                });


            });
     </script>
     <script class="cb-main-support global-file" src="/main/responsive-header/bootstrap-custom/js/bootstrap.js">
     </script>
     <script class="cb-main-support global-file" src="/main/responsive-header/js/typeahead.js">
     </script>
     <!-- START OF CENSUS HEADER HERE -->
     <div id="innerPage">
      <div class="belowHeader">
       <div class="topBg">
       </div>
       <div class="wrapper wrapperMarginTop">
        <div class="desktopHeaderCls row no-gutter" id="desktopHeader">
         <div class="censusheader col-lg-12">
          <div class="cb-header-tr cf" id="headerTopRow">
           <ul class="header_top_links">
            <li>
             <a href="https://www.commerce.gov/">
              U.S. Department of
                                            Commerce
             </a>
            </li>
            <li>
             <a href="https://www.census.gov/about/contact-us/social_media.html">
              Blogs
             </a>
            </li>
            <li>
             <a href="https://www.census.gov/about/index.html">
              Index
                                            A-Z
             </a>
            </li>
            <li>
             <a href="https://www.census.gov/glossary/">
              Glossary
             </a>
            </li>
            <li>
             <a href="https://ask.census.gov/">
              FAQs
             </a>
            </li>
           </ul>
          </div>
          <div class="cb-header-br cf" id="bottomRow">
           <div class="cb-header-logo col-sm-1">
            <div id="logo">
             <a href="https://www.census.gov/en.html">
              <img alt="United States Census Bureau" src="/main/img/USCENSUS_IDENTITY_SOLO_White_2in_TM.svg" title="U.S. Census Bureau"/>
             </a>
            </div>
           </div>
           <div class="col-sm-9 main-nav-section" id="mainNavSection">
            <nav>
             <div id="unknown">
              <!-- BEGINNING OF NAVIGATION TABS -->
              <div id="headerBottomRow">
               <ul class="nav nav-tabs clickable" id="mainTabs">
                <li class="headerCategories" id="NAV_1784167100_1HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_11" onclick="toggleDropdown(event, '#NAV_1784167100_1');">
                  <div class="top_header">
                   TOPICS
                  </div>
                  <div class="subHeader">
                   Population, Economy
                  </div>
                 </a>
                </li>
                <li class="headerCategories" id="NAV_1059285156_2HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_12" onclick="toggleDropdown(event, '#NAV_1059285156_2');">
                  <div class="top_header">
                   GEOGRAPHY
                  </div>
                  <div class="subHeader">
                   Maps, Products
                  </div>
                 </a>
                </li>
                <li class="headerCategories" id="NAV_1830861979_3HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_13" onclick="toggleDropdown(event, '#NAV_1830861979_3');">
                  <div class="top_header">
                   LIBRARY
                  </div>
                  <div class="subHeader">
                   Infographics, Publications
                  </div>
                 </a>
                </li>
                <li class="headerCategories" id="NAV_2122698_4HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_14" onclick="toggleDropdown(event, '#NAV_2122698_4');">
                  <div class="top_header">
                   DATA
                  </div>
                  <div class="subHeader">
                   Tools, Developers
                  </div>
                 </a>
                </li>
                <li class="headerCategories" id="NAV_542684251_5HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_15" onclick="toggleDropdown(event, '#NAV_542684251_5');">
                  <div class="top_header">
                   SURVEYS/PROGRAMS
                  </div>
                  <div class="subHeader">
                   Respond, Survey Data
                  </div>
                 </a>
                </li>
                <li class="headerCategories" id="NAV_1460391502_6HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_16" onclick="toggleDropdown(event, '#NAV_1460391502_6');">
                  <div class="top_header">
                   NEWSROOM
                  </div>
                  <div class="subHeader">
                   News, Blogs
                  </div>
                 </a>
                </li>
                <li class="headerCategories" id="NAV_1683946577_7HeaderItem">
                 <a class="accessibleLink" href="#" id="anch_17" onclick="toggleDropdown(event, '#NAV_1683946577_7');">
                  <div class="top_header">
                   ABOUT US
                  </div>
                  <div class="subHeader">
                   Our Research
                  </div>
                 </a>
                </li>
               </ul>
              </div>
              <!-- END OF NAVIGATION TABS -->
             </div>
            </nav>
           </div>
           <div class="col-sm-1 cb-head-search" id='searchInputBox"'>
            <div class="searchform">
             <form action="/search-results.html" id="searchForm" method="get">
              <fieldset>
               <legend class="sr-only">
                Search the Census website
               </legend>
               <div class="searchbox">
                <label>
                 <span class="sr-only" for="sedarchbox">
                  Enter a term to search on the Census website
                 </span>
                 <input autocomplete="off" id="searchbox" name="q" onblur="if(this.value==''){this.value='Search'}" onfocus="if(this.value=='Search'){this.value=''}" type="text" value="Search"/>
                 <span aria-live="polite" class="ui-help-hidden-accessible" role="status">
                 </span>
                </label>
               </div>
               <input name="page" type="hidden" value="1"/>
               <input id="stateGeo" name="stateGeo" type="hidden" value="none"/>
               <input name="searchtype" type="hidden" value="web"/>
               <input name="cssp" type="hidden" value="SERP"/>
              </fieldset>
             </form>
            </div>
           </div>
          </div>
          <div class="topnavigation topnavdropdown">
           <!-- Body for header elements -->
           <!-- TOPICS TAB BEGINS -->
           <div class="linksDropDown col-lg-12 clearfx" id="NAV_1784167100_1" style="display:none">
            <!-- Topics 2nd level menu, 1st row -->
            <div class="subCategoriesContainer">
             <ul class="nav nav-pills">
              <li class="categories subCategoryButton">
               <a class="accessibleLink" data-target="#NAV_30093459_0TabContent" data-toggle="tab" id="NAV_30093459_0TabLink" onclick="showTab(this);">
                Population
                <span class="glyphicon glyphicon-menu-down" style="font-size: 10px;">
                </span>
               </a>
              </li>
              <li class="categories subCategoryButton">
               <a class="accessibleLink" data-target="#NAV_246571490_0TabContent" data-toggle="tab" id="NAV_246571490_0TabLink" onclick="showTab(this);">
                Economy
                <span class="glyphicon glyphicon-menu-down" style="font-size: 10px;">
                </span>
               </a>
              </li>
              <li class="categories subCategoryButton">
               <a class="accessibleLink" data-target="#NAV_1082186784_0TabContent" data-toggle="tab" id="NAV_1082186784_0TabLink" onclick="showTab(this);">
                Business
                <span class="glyphicon glyphicon-menu-down" style="font-size: 10px;">
                </span>
               </a>
              </li>
              <li class="categories subCategoryButton">
               <a class="accessibleLink" data-target="#NAV_1713211272_0TabContent" data-toggle="tab" id="NAV_1713211272_0TabLink" onclick="showTab(this);">
                Education
                <span class="glyphicon glyphicon-menu-down" style="font-size: 10px;">
                </span>
               </a>
              </li>
             </ul>
             <div class="row tab-content">
              <!--Population begins -->
              <div class="tab-pane fade subCategoryPane" id="NAV_30093459_0TabContent">
               <div class="kicker col-lg-6">
                <p>
                 Our population statistics cover age,
                                                        sex,
                                                        race,
                                                        Hispanic origin, migration, ancestry, language use, veterans, as
                                                        well as
                                                        population estimates and projections.
                </p>
                <div class="row">
                 <div class="col-lg-6">
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population.html">
                    Population Main
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/about.html">
                    About the Population
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/data.html">
                    Data
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/news.html">
                    News
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/publications.html">
                    Population Publications
                   </a>
                  </div>
                 </div>
                 <div class="col-lg-6">
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/stories.html">
                    Population Stories
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/videos.html">
                    Population Videos
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/visualizations.html">
                    Population Visualizations
                   </a>
                  </div>
                  <div class="kickerLink" style="white-space: nowrap;">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/working-papers.html">
                    Population Working Papers
                   </a>
                  </div>
                  <div class="kickerLink">
                   <a class="accessibleLink" href="https://www.census.gov/topics/population/surveys.html">
                    Surveys/Programs
                   </a>
                  </div>
                 </div>
                </div>
               </div>
               <div class="subLinks col-lg-6">
                <div class="row">
                 <div class="col-lg-6">
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/age-and-sex.html">
                    Age and Sex
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/ancestry.html">
                    Ancestry
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/children.html">
                    Children
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/computer-internet.html">
                    Computer and Internet Use
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/foreign-born.html">
                    Foreign Born
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/hispanic-origin.html">
                    Hispanic Origin
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/international.html">
                    International
                   </a>
                  </div>
                 </div>
                 <div class="col-lg-6">
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/language-use.html">
                    Language Use
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/migration.html">
                    Migration/Geographic Mobility
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/population-estimates.html">
                    Population Estimates
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/population-projections.html">
                    Population Projections
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/race.html">
                    Race
                   </a>
                  </div>
                  <div class="subLink">
                   <a class="accessibleLink" href="//www.census.gov/topics/population/veterans.html">
                    Veterans
                   </a>
                  </div>

In [4]:
My_table = soup.findAll("td")
str_cells = str(My_table)
cleantext = BeautifulSoup(str_cells, "lxml").get_text()
print(cleantext)

[  January   2019  ,           7,134.3  ,          41,603.8  ,         -34,469.5  ,   February  2019  ,           8,433.6  ,          33,194.4  ,         -24,760.8  ,   March     2019  ,          10,426.5  ,          31,175.7  ,         -20,749.1  ,   April     2019  ,           7,896.3  ,          34,798.9  ,         -26,902.6  ,  TOTAL     2019 ,         33,890.8 ,        140,772.8 ,       -106,882.1 ,   January   2018  ,           9,902.6  ,          45,765.6  ,         -35,863.1  ,   February  2018  ,           9,759.9  ,          39,020.6  ,         -29,260.7  ,   March     2018  ,          12,652.1  ,          38,327.6  ,         -25,675.5  ,   April     2018  ,          10,503.8  ,          38,303.9  ,         -27,800.1  ,   May       2018  ,          10,428.2  ,          43,965.7  ,         -33,537.5  ,   June      2018  ,          10,860.1  ,          44,612.1  ,         -33,752.0  ,   July      2018  ,          10,134.6  ,          47,120.6  ,         -36,986.0  ,   August    2018  ,           9,285.9  ,          47,869.2  ,         -38,583.3  ,   September 2018  ,           9,730.0  ,          50,015.0  ,         -40,285.0  ,   October   2018  ,           9,139.9  ,          52,202.3  ,         -43,062.5  ,   November  2018  ,           8,606.2  ,          46,500.8  ,         -37,894.6  ,   December  2018  ,           9,144.9  ,          45,972.1  ,         -36,827.2  ,  TOTAL     2018 ,        120,148.1 ,        539,675.6 ,       -419,527.4 ,   January   2017  ,           9,955.5  ,          41,339.3  ,         -31,383.8  ,   February  2017  ,           9,739.8  ,          32,788.3  ,         -23,048.5  ,   March     2017  ,           9,720.1  ,          34,162.7  ,         -24,442.6  ,   April     2017  ,           9,806.6  ,          37,443.2  ,         -27,636.7  ,   May       2017  ,           9,880.1  ,          41,760.6  ,         -31,880.6  ,   June      2017  ,           9,718.5  ,          42,261.4  ,         -32,542.9  ,   July      2017  ,           9,955.2  ,          43,565.9  ,         -33,610.7  ,   August    2017  ,          10,824.5  ,          45,788.1  ,         -34,963.6  ,   September 2017  ,          10,896.0  ,          45,409.0  ,         -34,513.1  ,   October   2017  ,          12,963.7  ,          48,137.7  ,         -35,174.0  ,   November  2017  ,          12,707.4  ,          48,107.7  ,         -35,400.3  ,   December  2017  ,          13,630.3  ,          44,456.4  ,         -30,826.1  ,  TOTAL     2017 ,        129,797.6 ,        505,220.2 ,       -375,422.6 ,   January   2016  ,           8,208.9  ,          37,126.4  ,         -28,917.5  ,   February  2016  ,           8,080.5  ,          36,066.9  ,         -27,986.4  ,   March     2016  ,           8,925.6  ,          29,812.3  ,         -20,886.8  ,   April     2016  ,           8,679.7  ,          32,920.2  ,         -24,240.5  ,   May       2016  ,           8,542.0  ,          37,513.7  ,         -28,971.8  ,   June      2016  ,           8,845.6  ,          38,539.2  ,         -29,693.6  ,   July      2016  ,           9,129.7  ,          39,438.9  ,         -30,309.2  ,   August    2016  ,           9,372.9  ,          43,221.8  ,         -33,848.9  ,   September 2016  ,           9,521.2  ,          42,020.9  ,         -32,499.8  ,   October   2016  ,          12,600.0  ,          43,798.1  ,         -31,198.1  ,   November  2016  ,          12,044.1  ,          42,602.6  ,         -30,558.5  ,   December  2016  ,          11,644.8  ,          39,358.9  ,         -27,714.1  ,  TOTAL     2016 ,        115,594.8 ,        462,420.0 ,       -346,825.2 ,   January   2015  ,           9,459.2  ,          38,589.7  ,         -29,130.5  ,   February  2015  ,           8,754.6  ,          31,564.0  ,         -22,809.4  ,   March     2015  ,           9,886.5  ,          41,136.9  ,         -31,250.4  ,   April     2015  ,           9,279.9  ,          36,121.4  ,         -26,841.5  ,   May       2015  ,           8,749.8  ,          39,082.0  ,         -30,332.2  ,   June      2015  ,           9,615.8  ,          41,453.8  ,         -31,838.1  ,   July      2015  ,           9,505.2  ,          41,215.1  ,         -31,709.9  ,   August    2015  ,           9,183.5  ,          44,138.1  ,         -34,954.6  ,   September 2015  ,           9,419.4  ,          45,725.0  ,         -36,305.5  ,   October   2015  ,          11,324.9  ,          44,309.9  ,         -32,985.1  ,   November  2015  ,          10,603.6  ,          41,884.8  ,         -31,281.2  ,   December  2015  ,          10,091.1  ,          37,981.0  ,         -27,889.9  ,  TOTAL     2015 ,        115,873.4 ,        483,201.7 ,       -367,328.3 ,   January   2014  ,          10,264.5  ,          38,377.2  ,         -28,112.7  ,   February  2014  ,           9,750.7  ,          30,700.4  ,         -20,949.7  ,   March     2014  ,          10,934.3  ,          31,420.9  ,         -20,486.6  ,   April     2014  ,           9,031.9  ,          36,450.2  ,         -27,418.3  ,   May       2014  ,           9,220.2  ,          38,188.1  ,         -28,968.0  ,   June      2014  ,           9,330.2  ,          39,607.1  ,         -30,276.9  ,   July      2014  ,           9,291.8  ,          40,319.6  ,         -31,027.8  ,   August    2014  ,           9,625.2  ,          40,093.8  ,         -30,468.6  ,   September 2014  ,           9,314.0  ,          45,102.8  ,         -35,788.8  ,   October   2014  ,          12,593.3  ,          45,335.4  ,         -32,742.0  ,   November  2014  ,          12,125.9  ,          42,483.5  ,         -30,357.6  ,   December  2014  ,          12,175.2  ,          40,395.9  ,         -28,220.7  ,  TOTAL     2014 ,        123,657.2 ,        468,474.9 ,       -344,817.7 ,   January   2013  ,           9,382.9  ,          37,193.7  ,         -27,810.7  ,   February  2013  ,           9,133.3  ,          32,742.7  ,         -23,609.4  ,   March     2013  ,           9,539.0  ,          27,294.1  ,         -17,755.0  ,   April     2013  ,           8,954.0  ,          33,131.9  ,         -24,178.0  ,   May       2013  ,           8,752.8  ,          36,617.6  ,         -27,864.8  ,   June      2013  ,           9,217.6  ,          35,886.0  ,         -26,668.4  ,   July      2013  ,           8,723.7  ,          38,800.4  ,         -30,076.7  ,   August    2013  ,           9,352.1  ,          39,161.3  ,         -29,809.2  ,   September 2013  ,           9,527.2  ,          40,144.4  ,         -30,617.2  ,   October   2013  ,          13,147.8  ,          41,845.5  ,         -28,697.7  ,   November  2013  ,          13,027.1  ,          40,112.3  ,         -27,085.2  ,   December  2013  ,          12,988.7  ,          37,500.2  ,         -24,511.6  ,  TOTAL     2013 ,        121,746.2 ,        440,430.0 ,       -318,683.8 ,   January   2012  ,           8,359.5  ,          34,417.5  ,         -26,058.1  ,   February  2012  ,           8,785.7  ,          28,105.2  ,         -19,319.5  ,   March     2012  ,           9,811.6  ,          31,431.3  ,         -21,619.8  ,   April     2012  ,           8,468.1  ,          33,016.3  ,         -24,548.1  ,   May       2012  ,           8,960.2  ,          34,937.8  ,         -25,977.7  ,   June      2012  ,           8,478.1  ,          35,949.4  ,         -27,471.2  ,   July      2012  ,           8,515.1  ,          37,930.8  ,         -29,415.7  ,   August    2012  ,           8,613.3  ,          37,280.6  ,         -28,667.3  ,   September 2012  ,           8,804.2  ,          37,891.8  ,         -29,087.6  ,   October   2012  ,          10,824.4  ,          40,257.1  ,         -29,432.7  ,   November  2012  ,          10,587.8  ,          39,543.7  ,         -28,955.9  ,   December  2012  ,          10,308.6  ,          34,857.6  ,         -24,548.9  ,  TOTAL     2012 ,        110,516.6 ,        425,619.1 ,       -315,102.5 ,   January   2011  ,           8,017.8  ,          31,377.4  ,         -23,359.6  ,   February  2011  ,           8,383.3  ,          27,244.7  ,         -18,861.4  ,   March     2011  ,           9,563.7  ,          27,599.7  ,         -18,035.9  ,   April     2011  ,           8,000.5  ,          29,580.3  ,         -21,579.8  ,   May       2011  ,           7,849.2  ,          32,788.1  ,         -24,938.9  ,   June      2011  ,           7,867.0  ,          34,374.8  ,         -26,507.8  ,   July      2011  ,           8,157.9  ,          35,152.2  ,         -26,994.3  ,   August    2011  ,           8,421.6  ,          37,374.1  ,         -28,952.5  ,   September 2011  ,           8,370.1  ,          36,418.6  ,         -28,048.6  ,   October   2011  ,           9,745.6  ,          37,824.1  ,         -28,078.5  ,   November  2011  ,           9,997.2  ,          36,764.9  ,         -26,767.7  ,   December  2011  ,           9,747.7  ,          32,872.3  ,         -23,124.6  ,  TOTAL     2011 ,        104,121.5 ,        399,371.2 ,       -295,249.7 ,   January   2010  ,           6,898.4  ,          25,215.9  ,         -18,317.6  ,   February  2010  ,           6,840.2  ,          23,342.8  ,         -16,502.6  ,   March     2010  ,           7,400.8  ,          24,292.2  ,         -16,891.4  ,   April     2010  ,           6,600.7  ,          25,920.2  ,         -19,319.5  ,   May       2010  ,           6,755.3  ,          29,052.4  ,         -22,297.2  ,   June      2010  ,           6,733.7  ,          32,843.1  ,         -26,109.4  ,   July      2010  ,           7,339.3  ,          33,266.8  ,         -25,927.6  ,   August    2010  ,           7,209.7  ,          35,375.3  ,         -28,165.6  ,   September 2010  ,           7,114.3  ,          35,196.7  ,         -28,082.4  ,   October   2010  ,           9,417.3  ,          35,083.3  ,         -25,666.0  ,   November  2010  ,           9,475.8  ,          34,564.3  ,         -25,088.4  ,   December  2010  ,          10,125.6  ,          30,799.6  ,         -20,674.0  ,  TOTAL     2010 ,         91,911.1 ,        364,952.6 ,       -273,041.6 ,   January   2009  ,           4,159.6  ,          24,743.5  ,         -20,583.8  ,   February  2009  ,           4,661.7  ,          18,845.5  ,         -14,183.8  ,   March     2009  ,           5,579.3  ,          21,224.7  ,         -15,645.5  ,   April     2009  ,           5,161.4  ,          21,920.6  ,         -16,759.2  ,   May       2009  ,           5,256.0  ,          22,734.1  ,         -17,478.1  ,   June      2009  ,           5,548.6  ,          23,972.8  ,         -18,424.2  ,   July      2009  ,           5,269.3  ,          25,671.1  ,         -20,401.8  ,   August    2009  ,           5,518.0  ,          25,798.1  ,         -20,280.1  ,   September 2009  ,           5,764.3  ,          27,893.9  ,         -22,129.6  ,   October   2009  ,           6,879.3  ,          29,557.8  ,         -22,678.5  ,   November  2009  ,           7,374.2  ,          27,541.7  ,         -20,167.6  ,   December  2009  ,           8,325.0  ,          26,470.1  ,         -18,145.1  ,  TOTAL     2009 ,         69,496.7 ,        296,373.9 ,       -226,877.2 ,   January   2008  ,           5,556.7  ,          26,193.0  ,         -20,636.3  ,   February  2008  ,           5,698.1  ,          24,095.9  ,         -18,397.8  ,   March     2008  ,           6,294.4  ,          22,440.2  ,         -16,145.9  ,   April     2008  ,           5,651.2  ,          25,951.7  ,         -20,300.4  ,   May       2008  ,           6,275.7  ,          27,634.5  ,         -21,358.9  ,   June      2008  ,           6,188.2  ,          27,930.6  ,         -21,742.5  ,   July      2008  ,           6,234.6  ,          31,247.3  ,         -25,012.6  ,   August    2008  ,           6,201.3  ,          31,823.7  ,         -25,622.4  ,   September 2008  ,           5,257.6  ,          33,078.7  ,         -27,821.1  ,   October   2008  ,           6,083.4  ,          34,032.4  ,         -27,949.0  ,   November  2008  ,           5,181.0  ,          28,265.0  ,         -23,084.1  ,   December  2008  ,           5,110.7  ,          25,079.5  ,         -19,968.8  ,  TOTAL     2008 ,         69,732.8 ,        337,772.6 ,       -268,039.8 ,   January   2007  ,           4,389.5  ,          25,640.6  ,         -21,251.0  ,   February  2007  ,           4,532.9  ,          23,038.9  ,         -18,506.0  ,   March     2007  ,           5,425.4  ,          22,723.0  ,         -17,297.7  ,   April     2007  ,           4,704.0  ,          24,241.5  ,         -19,537.6  ,   May       2007  ,           5,129.4  ,          25,290.6  ,         -20,161.1  ,   June      2007  ,           5,561.8  ,          27,071.0  ,         -21,509.2  ,   July      2007  ,           4,665.9  ,          28,601.2  ,         -23,935.2  ,   August    2007  ,           5,552.8  ,          28,424.5  ,         -22,871.7  ,   September 2007  ,           5,311.9  ,          29,419.0  ,         -24,107.1  ,   October   2007  ,           5,532.9  ,          31,555.4  ,         -26,022.5  ,   November  2007  ,           5,581.5  ,          29,780.7  ,         -24,199.2  ,   December  2007  ,           6,548.9  ,          25,656.6  ,         -19,107.7  ,  TOTAL     2007 ,         62,936.9 ,        321,442.9 ,       -258,506.0 ,   January   2006  ,           3,396.9  ,          21,382.5  ,         -17,985.6  ,   February  2006  ,           4,072.2  ,          17,905.4  ,         -13,833.1  ,   March     2006  ,           4,867.1  ,          20,531.3  ,         -15,664.2  ,   April     2006  ,           4,232.4  ,          21,459.1  ,         -17,226.7  ,   May       2006  ,           4,434.1  ,          22,317.6  ,         -17,883.5  ,   June      2006  ,           4,302.9  ,          23,989.7  ,         -19,686.8  ,   July      2006  ,           4,806.3  ,          24,632.0  ,         -19,825.7  ,   August    2006  ,           4,603.3  ,          26,713.3  ,         -22,110.1  ,   September 2006  ,           4,461.0  ,          27,570.6  ,         -23,109.6  ,   October   2006  ,           4,885.3  ,          29,388.6  ,         -24,503.3  ,   November  2006  ,           4,595.8  ,          27,775.1  ,         -23,179.3  ,   December  2006  ,           5,015.8  ,          24,109.2  ,         -19,093.4  ,  TOTAL     2006 ,         53,673.0 ,        287,774.4 ,       -234,101.3 ,   January   2005  ,           2,609.3  ,          17,885.8  ,         -15,276.5  ,   February  2005  ,           3,058.1  ,          16,937.6  ,         -13,879.5  ,   March     2005  ,           3,336.4  ,          16,184.9  ,         -12,848.6  ,   April     2005  ,           3,263.7  ,          18,148.5  ,         -14,884.8  ,   May       2005  ,           3,222.9  ,          19,053.2  ,         -15,830.3  ,   June      2005  ,           3,370.7  ,          20,976.7  ,         -17,606.0  ,   July      2005  ,           3,560.0  ,          21,272.7  ,         -17,712.7  ,   August    2005  ,           3,728.7  ,          22,421.3  ,         -18,692.6  ,   September 2005  ,           3,165.8  ,          23,294.5  ,         -20,128.7  ,   October   2005  ,           3,899.2  ,          24,382.9  ,         -20,483.7  ,   November  2005  ,           3,807.5  ,          22,426.1  ,         -18,618.6  ,   December  2005  ,           4,169.8  ,          20,486.0  ,         -16,316.2  ,  TOTAL     2005 ,         41,192.0 ,        243,470.1 ,       -202,278.1 ,   January   2004  ,           2,620.5  ,          14,089.0  ,         -11,468.5  ,   February  2004  ,           2,929.0  ,          11,267.1  ,          -8,338.2  ,   March     2004  ,           3,361.9  ,          13,800.1  ,         -10,438.2  ,   April     2004  ,           2,734.6  ,          14,744.8  ,         -12,010.2  ,   May       2004  ,           2,835.1  ,          15,067.1  ,         -12,232.1  ,   June      2004  ,           2,764.2  ,          16,887.8  ,         -14,123.5  ,   July      2004  ,           2,618.8  ,          17,562.1  ,         -14,943.3  ,   August    2004  ,           2,621.0  ,          18,067.9  ,         -15,446.9  ,   September 2004  ,           2,823.1  ,          18,386.9  ,         -15,563.9  ,   October   2004  ,           2,946.7  ,          19,718.2  ,         -16,771.4  ,   November  2004  ,           2,938.2  ,          19,679.0  ,         -16,740.8  ,   December  2004  ,           3,234.8  ,          17,412.0  ,         -14,177.2  ,  TOTAL     2004 ,         34,427.8 ,        196,682.0 ,       -162,254.3 ,   January   2003  ,           2,069.8  ,          11,403.5  ,          -9,333.7  ,   February  2003  ,           2,048.7  ,           9,629.6  ,          -7,581.0  ,   March     2003  ,           2,423.1  ,          10,110.0  ,          -7,686.9  ,   April     2003  ,           2,121.9  ,          11,521.9  ,          -9,399.9  ,   May       2003  ,           1,984.3  ,          11,884.7  ,          -9,900.4  ,   June      2003  ,           2,119.6  ,          12,127.3  ,         -10,007.7  ,   July      2003  ,           2,067.4  ,          13,438.6  ,         -11,371.2  ,   August    2003  ,           2,034.4  ,          13,764.9  ,         -11,730.4  ,   September 2003  ,           2,091.0  ,          14,747.5  ,         -12,656.5  ,   October   2003  ,           2,778.3  ,          16,458.3  ,         -13,680.0  ,   November  2003  ,           3,319.7  ,          14,156.9  ,         -10,837.3  ,   December  2003  ,           3,309.6  ,          13,192.8  ,          -9,883.2  ,  TOTAL     2003 ,         28,367.9 ,        152,436.1 ,       -124,068.2 ,   January   2002  ,           1,569.3  ,           8,415.4  ,          -6,846.1  ,   February  2002  ,           1,529.5  ,           8,020.8  ,          -6,491.3  ,   March     2002  ,           1,620.5  ,           7,259.0  ,          -5,638.5  ,   April     2002  ,           1,544.5  ,           9,097.6  ,          -7,553.1  ,   May       2002  ,           1,773.9  ,           9,846.9  ,          -8,073.0  ,   June      2002  ,           2,205.9  ,          10,727.2  ,          -8,521.3  ,   July      2002  ,           1,848.0  ,          11,213.2  ,          -9,365.2  ,   August    2002  ,           1,839.8  ,          12,671.4  ,         -10,831.6  ,   September 2002  ,           2,023.7  ,          12,291.5  ,         -10,267.8  ,   October   2002  ,           1,962.7  ,          11,455.0  ,          -9,492.3  ,   November  2002  ,           2,160.8  ,          12,569.6  ,         -10,408.8  ,   December  2002  ,           2,049.1  ,          11,625.0  ,          -9,575.9  ,  TOTAL     2002 ,         22,127.7 ,        125,192.6 ,       -103,064.9 ,   January   2001  ,           1,187.5  ,           8,427.5  ,          -7,240.0  ,   February  2001  ,           1,289.8  ,           6,375.6  ,          -5,085.8  ,   March     2001  ,           1,855.8  ,           7,590.2  ,          -5,734.4  ,   April     2001  ,           1,398.9  ,           7,686.8  ,          -6,287.9  ,   May       2001  ,           1,596.0  ,           7,757.9  ,          -6,161.9  ,   June      2001  ,           1,786.4  ,           8,398.2  ,          -6,611.8  ,   July      2001  ,           1,487.0  ,           8,975.3  ,          -7,488.3  ,   August    2001  ,           1,929.7  ,          10,042.9  ,          -8,113.2  ,   September 2001  ,           1,427.8  ,           9,927.8  ,          -8,500.0  ,   October   2001  ,           1,647.7  ,          10,808.3  ,          -9,160.6  ,   November  2001  ,           1,674.5  ,           8,878.8  ,          -7,204.3  ,   December  2001  ,           1,901.2  ,           7,409.1  ,          -5,507.9  ,  TOTAL     2001 ,         19,182.3 ,        102,278.4 ,        -83,096.1 ,   January   2000  ,             863.1  ,           6,902.1  ,          -6,039.0  ,   February  2000  ,             972.7  ,           6,584.4  ,          -5,611.7  ,   March     2000  ,           1,330.5  ,           6,424.1  ,          -5,093.6  ,   April     2000  ,           1,227.5  ,           7,070.5  ,    

In [5]:
cleantext=" ".join(cleantext.split())
cleantext

'[ January 2019 , 7,134.3 , 41,603.8 , -34,469.5 , February 2019 , 8,433.6 , 33,194.4 , -24,760.8 , March 2019 , 10,426.5 , 31,175.7 , -20,749.1 , April 2019 , 7,896.3 , 34,798.9 , -26,902.6 , TOTAL 2019 , 33,890.8 , 140,772.8 , -106,882.1 , January 2018 , 9,902.6 , 45,765.6 , -35,863.1 , February 2018 , 9,759.9 , 39,020.6 , -29,260.7 , March 2018 , 12,652.1 , 38,327.6 , -25,675.5 , April 2018 , 10,503.8 , 38,303.9 , -27,800.1 , May 2018 , 10,428.2 , 43,965.7 , -33,537.5 , June 2018 , 10,860.1 , 44,612.1 , -33,752.0 , July 2018 , 10,134.6 , 47,120.6 , -36,986.0 , August 2018 , 9,285.9 , 47,869.2 , -38,583.3 , September 2018 , 9,730.0 , 50,015.0 , -40,285.0 , October 2018 , 9,139.9 , 52,202.3 , -43,062.5 , November 2018 , 8,606.2 , 46,500.8 , -37,894.6 , December 2018 , 9,144.9 , 45,972.1 , -36,827.2 , TOTAL 2018 , 120,148.1 , 539,675.6 , -419,527.4 , January 2017 , 9,955.5 , 41,339.3 , -31,383.8 , February 2017 , 9,739.8 , 32,788.3 , -23,048.5 , March 2017 , 9,720.1 , 34,162.7 , -24,442.6 , April 2017 , 9,806.6 , 37,443.2 , -27,636.7 , May 2017 , 9,880.1 , 41,760.6 , -31,880.6 , June 2017 , 9,718.5 , 42,261.4 , -32,542.9 , July 2017 , 9,955.2 , 43,565.9 , -33,610.7 , August 2017 , 10,824.5 , 45,788.1 , -34,963.6 , September 2017 , 10,896.0 , 45,409.0 , -34,513.1 , October 2017 , 12,963.7 , 48,137.7 , -35,174.0 , November 2017 , 12,707.4 , 48,107.7 , -35,400.3 , December 2017 , 13,630.3 , 44,456.4 , -30,826.1 , TOTAL 2017 , 129,797.6 , 505,220.2 , -375,422.6 , January 2016 , 8,208.9 , 37,126.4 , -28,917.5 , February 2016 , 8,080.5 , 36,066.9 , -27,986.4 , March 2016 , 8,925.6 , 29,812.3 , -20,886.8 , April 2016 , 8,679.7 , 32,920.2 , -24,240.5 , May 2016 , 8,542.0 , 37,513.7 , -28,971.8 , June 2016 , 8,845.6 , 38,539.2 , -29,693.6 , July 2016 , 9,129.7 , 39,438.9 , -30,309.2 , August 2016 , 9,372.9 , 43,221.8 , -33,848.9 , September 2016 , 9,521.2 , 42,020.9 , -32,499.8 , October 2016 , 12,600.0 , 43,798.1 , -31,198.1 , November 2016 , 12,044.1 , 42,602.6 , -30,558.5 , December 2016 , 11,644.8 , 39,358.9 , -27,714.1 , TOTAL 2016 , 115,594.8 , 462,420.0 , -346,825.2 , January 2015 , 9,459.2 , 38,589.7 , -29,130.5 , February 2015 , 8,754.6 , 31,564.0 , -22,809.4 , March 2015 , 9,886.5 , 41,136.9 , -31,250.4 , April 2015 , 9,279.9 , 36,121.4 , -26,841.5 , May 2015 , 8,749.8 , 39,082.0 , -30,332.2 , June 2015 , 9,615.8 , 41,453.8 , -31,838.1 , July 2015 , 9,505.2 , 41,215.1 , -31,709.9 , August 2015 , 9,183.5 , 44,138.1 , -34,954.6 , September 2015 , 9,419.4 , 45,725.0 , -36,305.5 , October 2015 , 11,324.9 , 44,309.9 , -32,985.1 , November 2015 , 10,603.6 , 41,884.8 , -31,281.2 , December 2015 , 10,091.1 , 37,981.0 , -27,889.9 , TOTAL 2015 , 115,873.4 , 483,201.7 , -367,328.3 , January 2014 , 10,264.5 , 38,377.2 , -28,112.7 , February 2014 , 9,750.7 , 30,700.4 , -20,949.7 , March 2014 , 10,934.3 , 31,420.9 , -20,486.6 , April 2014 , 9,031.9 , 36,450.2 , -27,418.3 , May 2014 , 9,220.2 , 38,188.1 , -28,968.0 , June 2014 , 9,330.2 , 39,607.1 , -30,276.9 , July 2014 , 9,291.8 , 40,319.6 , -31,027.8 , August 2014 , 9,625.2 , 40,093.8 , -30,468.6 , September 2014 , 9,314.0 , 45,102.8 , -35,788.8 , October 2014 , 12,593.3 , 45,335.4 , -32,742.0 , November 2014 , 12,125.9 , 42,483.5 , -30,357.6 , December 2014 , 12,175.2 , 40,395.9 , -28,220.7 , TOTAL 2014 , 123,657.2 , 468,474.9 , -344,817.7 , January 2013 , 9,382.9 , 37,193.7 , -27,810.7 , February 2013 , 9,133.3 , 32,742.7 , -23,609.4 , March 2013 , 9,539.0 , 27,294.1 , -17,755.0 , April 2013 , 8,954.0 , 33,131.9 , -24,178.0 , May 2013 , 8,752.8 , 36,617.6 , -27,864.8 , June 2013 , 9,217.6 , 35,886.0 , -26,668.4 , July 2013 , 8,723.7 , 38,800.4 , -30,076.7 , August 2013 , 9,352.1 , 39,161.3 , -29,809.2 , September 2013 , 9,527.2 , 40,144.4 , -30,617.2 , October 2013 , 13,147.8 , 41,845.5 , -28,697.7 , November 2013 , 13,027.1 , 40,112.3 , -27,085.2 , December 2013 , 12,988.7 , 37,500.2 , -24,511.6 , TOTAL 2013 , 121,746.2 , 440,430.0 , -318,683.8 , January 2012 , 8,359.5 , 34,417.5 , -26,058.1 , February 2012 , 8,785.7 , 28,105.2 , -19,319.5 , March 2012 , 9,811.6 , 31,431.3 , -21,619.8 , April 2012 , 8,468.1 , 33,016.3 , -24,548.1 , May 2012 , 8,960.2 , 34,937.8 , -25,977.7 , June 2012 , 8,478.1 , 35,949.4 , -27,471.2 , July 2012 , 8,515.1 , 37,930.8 , -29,415.7 , August 2012 , 8,613.3 , 37,280.6 , -28,667.3 , September 2012 , 8,804.2 , 37,891.8 , -29,087.6 , October 2012 , 10,824.4 , 40,257.1 , -29,432.7 , November 2012 , 10,587.8 , 39,543.7 , -28,955.9 , December 2012 , 10,308.6 , 34,857.6 , -24,548.9 , TOTAL 2012 , 110,516.6 , 425,619.1 , -315,102.5 , January 2011 , 8,017.8 , 31,377.4 , -23,359.6 , February 2011 , 8,383.3 , 27,244.7 , -18,861.4 , March 2011 , 9,563.7 , 27,599.7 , -18,035.9 , April 2011 , 8,000.5 , 29,580.3 , -21,579.8 , May 2011 , 7,849.2 , 32,788.1 , -24,938.9 , June 2011 , 7,867.0 , 34,374.8 , -26,507.8 , July 2011 , 8,157.9 , 35,152.2 , -26,994.3 , August 2011 , 8,421.6 , 37,374.1 , -28,952.5 , September 2011 , 8,370.1 , 36,418.6 , -28,048.6 , October 2011 , 9,745.6 , 37,824.1 , -28,078.5 , November 2011 , 9,997.2 , 36,764.9 , -26,767.7 , December 2011 , 9,747.7 , 32,872.3 , -23,124.6 , TOTAL 2011 , 104,121.5 , 399,371.2 , -295,249.7 , January 2010 , 6,898.4 , 25,215.9 , -18,317.6 , February 2010 , 6,840.2 , 23,342.8 , -16,502.6 , March 2010 , 7,400.8 , 24,292.2 , -16,891.4 , April 2010 , 6,600.7 , 25,920.2 , -19,319.5 , May 2010 , 6,755.3 , 29,052.4 , -22,297.2 , June 2010 , 6,733.7 , 32,843.1 , -26,109.4 , July 2010 , 7,339.3 , 33,266.8 , -25,927.6 , August 2010 , 7,209.7 , 35,375.3 , -28,165.6 , September 2010 , 7,114.3 , 35,196.7 , -28,082.4 , October 2010 , 9,417.3 , 35,083.3 , -25,666.0 , November 2010 , 9,475.8 , 34,564.3 , -25,088.4 , December 2010 , 10,125.6 , 30,799.6 , -20,674.0 , TOTAL 2010 , 91,911.1 , 364,952.6 , -273,041.6 , January 2009 , 4,159.6 , 24,743.5 , -20,583.8 , February 2009 , 4,661.7 , 18,845.5 , -14,183.8 , March 2009 , 5,579.3 , 21,224.7 , -15,645.5 , April 2009 , 5,161.4 , 21,920.6 , -16,759.2 , May 2009 , 5,256.0 , 22,734.1 , -17,478.1 , June 2009 , 5,548.6 , 23,972.8 , -18,424.2 , July 2009 , 5,269.3 , 25,671.1 , -20,401.8 , August 2009 , 5,518.0 , 25,798.1 , -20,280.1 , September 2009 , 5,764.3 , 27,893.9 , -22,129.6 , October 2009 , 6,879.3 , 29,557.8 , -22,678.5 , November 2009 , 7,374.2 , 27,541.7 , -20,167.6 , December 2009 , 8,325.0 , 26,470.1 , -18,145.1 , TOTAL 2009 , 69,496.7 , 296,373.9 , -226,877.2 , January 2008 , 5,556.7 , 26,193.0 , -20,636.3 , February 2008 , 5,698.1 , 24,095.9 , -18,397.8 , March 2008 , 6,294.4 , 22,440.2 , -16,145.9 , April 2008 , 5,651.2 , 25,951.7 , -20,300.4 , May 2008 , 6,275.7 , 27,634.5 , -21,358.9 , June 2008 , 6,188.2 , 27,930.6 , -21,742.5 , July 2008 , 6,234.6 , 31,247.3 , -25,012.6 , August 2008 , 6,201.3 , 31,823.7 , -25,622.4 , September 2008 , 5,257.6 , 33,078.7 , -27,821.1 , October 2008 , 6,083.4 , 34,032.4 , -27,949.0 , November 2008 , 5,181.0 , 28,265.0 , -23,084.1 , December 2008 , 5,110.7 , 25,079.5 , -19,968.8 , TOTAL 2008 , 69,732.8 , 337,772.6 , -268,039.8 , January 2007 , 4,389.5 , 25,640.6 , -21,251.0 , February 2007 , 4,532.9 , 23,038.9 , -18,506.0 , March 2007 , 5,425.4 , 22,723.0 , -17,297.7 , April 2007 , 4,704.0 , 24,241.5 , -19,537.6 , May 2007 , 5,129.4 , 25,290.6 , -20,161.1 , June 2007 , 5,561.8 , 27,071.0 , -21,509.2 , July 2007 , 4,665.9 , 28,601.2 , -23,935.2 , August 2007 , 5,552.8 , 28,424.5 , -22,871.7 , September 2007 , 5,311.9 , 29,419.0 , -24,107.1 , October 2007 , 5,532.9 , 31,555.4 , -26,022.5 , November 2007 , 5,581.5 , 29,780.7 , -24,199.2 , December 2007 , 6,548.9 , 25,656.6 , -19,107.7 , TOTAL 2007 , 62,936.9 , 321,442.9 , -258,506.0 , January 2006 , 3,396.9 , 21,382.5 , -17,985.6 , February 2006 , 4,072.2 , 17,905.4 , -13,833.1 , March 2006 , 4,867.1 , 20,531.3 , -15,664.2 , April 2006 , 4,232.4 , 21,459.1 , -17,226.7 , May 2006 , 4,434.1 , 22,317.6 , -17,883.5 , June 2006 , 4,302.9 , 23,989.7 , -19,686.8 , July 2006 , 4,806.3 , 24,632.0 , -19,825.7 , August 2006 , 4,603.3 , 26,713.3 , -22,110.1 , September 2006 , 4,461.0 , 27,570.6 , -23,109.6 , October 2006 , 4,885.3 , 29,388.6 , -24,503.3 , November 2006 , 4,595.8 , 27,775.1 , -23,179.3 , December 2006 , 5,015.8 , 24,109.2 , -19,093.4 , TOTAL 2006 , 53,673.0 , 287,774.4 , -234,101.3 , January 2005 , 2,609.3 , 17,885.8 , -15,276.5 , February 2005 , 3,058.1 , 16,937.6 , -13,879.5 , March 2005 , 3,336.4 , 16,184.9 , -12,848.6 , April 2005 , 3,263.7 , 18,148.5 , -14,884.8 , May 2005 , 3,222.9 , 19,053.2 , -15,830.3 , June 2005 , 3,370.7 , 20,976.7 , -17,606.0 , July 2005 , 3,560.0 , 21,272.7 , -17,712.7 , August 2005 , 3,728.7 , 22,421.3 , -18,692.6 , September 2005 , 3,165.8 , 23,294.5 , -20,128.7 , October 2005 , 3,899.2 , 24,382.9 , -20,483.7 , November 2005 , 3,807.5 , 22,426.1 , -18,618.6 , December 2005 , 4,169.8 , 20,486.0 , -16,316.2 , TOTAL 2005 , 41,192.0 , 243,470.1 , -202,278.1 , January 2004 , 2,620.5 , 14,089.0 , -11,468.5 , February 2004 , 2,929.0 , 11,267.1 , -8,338.2 , March 2004 , 3,361.9 , 13,800.1 , -10,438.2 , April 2004 , 2,734.6 , 14,744.8 , -12,010.2 , May 2004 , 2,835.1 , 15,067.1 , -12,232.1 , June 2004 , 2,764.2 , 16,887.8 , -14,123.5 , July 2004 , 2,618.8 , 17,562.1 , -14,943.3 , August 2004 , 2,621.0 , 18,067.9 , -15,446.9 , September 2004 , 2,823.1 , 18,386.9 , -15,563.9 , October 2004 , 2,946.7 , 19,718.2 , -16,771.4 , November 2004 , 2,938.2 , 19,679.0 , -16,740.8 , December 2004 , 3,234.8 , 17,412.0 , -14,177.2 , TOTAL 2004 , 34,427.8 , 196,682.0 , -162,254.3 , January 2003 , 2,069.8 , 11,403.5 , -9,333.7 , February 2003 , 2,048.7 , 9,629.6 , -7,581.0 , March 2003 , 2,423.1 , 10,110.0 , -7,686.9 , April 2003 , 2,121.9 , 11,521.9 , -9,399.9 , May 2003 , 1,984.3 , 11,884.7 , -9,900.4 , June 2003 , 2,119.6 , 12,127.3 , -10,007.7 , July 2003 , 2,067.4 , 13,438.6 , -11,371.2 , August 2003 , 2,034.4 , 13,764.9 , -11,730.4 , September 2003 , 2,091.0 , 14,747.5 , -12,656.5 , October 2003 , 2,778.3 , 16,458.3 , -13,680.0 , November 2003 , 3,319.7 , 14,156.9 , -10,837.3 , December 2003 , 3,309.6 , 13,192.8 , -9,883.2 , TOTAL 2003 , 28,367.9 , 152,436.1 , -124,068.2 , January 2002 , 1,569.3 , 8,415.4 , -6,846.1 , February 2002 , 1,529.5 , 8,020.8 , -6,491.3 , March 2002 , 1,620.5 , 7,259.0 , -5,638.5 , April 2002 , 1,544.5 , 9,097.6 , -7,553.1 , May 2002 , 1,773.9 , 9,846.9 , -8,073.0 , June 2002 , 2,205.9 , 10,727.2 , -8,521.3 , July 2002 , 1,848.0 , 11,213.2 , -9,365.2 , August 2002 , 1,839.8 , 12,671.4 , -10,831.6 , September 2002 , 2,023.7 , 12,291.5 , -10,267.8 , October 2002 , 1,962.7 , 11,455.0 , -9,492.3 , November 2002 , 2,160.8 , 12,569.6 , -10,408.8 , December 2002 , 2,049.1 , 11,625.0 , -9,575.9 , TOTAL 2002 , 22,127.7 , 125,192.6 , -103,064.9 , January 2001 , 1,187.5 , 8,427.5 , -7,240.0 , February 2001 , 1,289.8 , 6,375.6 , -5,085.8 , March 2001 , 1,855.8 , 7,590.2 , -5,734.4 , April 2001 , 1,398.9 , 7,686.8 , -6,287.9 , May 2001 , 1,596.0 , 7,757.9 , -6,161.9 , June 2001 , 1,786.4 , 8,398.2 , -6,611.8 , July 2001 , 1,487.0 , 8,975.3 , -7,488.3 , August 2001 , 1,929.7 , 10,042.9 , -8,113.2 , September 2001 , 1,427.8 , 9,927.8 , -8,500.0 , October 2001 , 1,647.7 , 10,808.3 , -9,160.6 , November 2001 , 1,674.5 , 8,878.8 , -7,204.3 , December 2001 , 1,901.2 , 7,409.1 , -5,507.9 , TOTAL 2001 , 19,182.3 , 102,278.4 , -83,096.1 , January 2000 , 863.1 , 6,902.1 , -6,039.0 , February 2000 , 972.7 , 6,584.4 , -5,611.7 , March 2000 , 1,330.5 , 6,424.1 , -5,093.6 , April 2000 , 1,227.5 , 7,070.5 , -5,843.0 , May 2000 , 1,526.3 , 7,850.2 , -6,323.9 , June 2000 , 1,335.6 , 8,541.7 , -7,206.1 , July 2000 , 1,642.8 , 9,246.4 , -7,603.6 , August 2000 , 1,429.0 , 10,054.0 , -8,625.0 , September 2000 , 1,333.3 , 10,061.7 , -8,728.4 , October 2000 , 1,487.3 , 10,611.6 , -9,124.3 , November 2000 , 1,450.4 , 9,066.8 , -7,616.4 , December 2000 , 1,586.7 , 7,604.7 , -6,018.0 , TOTAL 2000 , 16,185.2 , 100,018.2 , -83,833.0 , January 1999 , 781.3 , 5,654.0 , -4,872.7 , February 1999 , 923.9 , 5,563.1 , -4,639.2 , March 1999 , 1,076.0 , 5,204.0 , -4,128.0 , April 1999 , 1,035.0 , 5,818.9 , -4,783.9 , May 1999 , 1,113.8 , 6,363.1 , -5,249.3 , June 1999 , 1,442.0 , 7,117.4 , -5,675.4 , July 1999 , 1,074.0 , 7,405.7 , -6,331.7 , August 1999 , 1,151.3 , 8,022.1 , -6,870.8 , September 1999 , 1,325.3 , 8,198.2 , -6,872.9 , October 1999 , 1,069.1 , 8,207.9 , -7,138.8 , November 1999 , 1,025.5 , 7,543.5 , -6,518.0 , December 1999 , 1,093.9 , 6,690.3 , -5,596.4 , TOTAL 1999 , 13,111.1 , 81,788.2 , -68,677.1 , January 1998 , 1,271.1 , 5,453.2 , -4,182.1 , February 1998 , 1,019.3 , 4,559.6 , -3,540.3 , March 1998 , 1,034.2 , 4,798.1 , -3,763.9 , April 1998 , 984.9 , 5,262.9 , -4,278.0 , May 1998 , 911.3 , 5,539.4 , -4,628.1 , June 1998 , 1,282.7 , 6,020.2 , -4,737.5 , July 1998 , 1,100.8 , 6,556.2 , -5,455.4 , August 1998 , 869.9 , 6,779.9 , -5,910.0 , September 1998 , 1,214.9 , 7,125.2 , -5,910.3 , October 1998 , 1,855.2 , 7,377.7 , -5,522.5 , November 1998 , 1,317.2 , 6,374.1 , -5,056.9 , December 1998 , 1,379.7 , 5,322.1 , -3,942.4 , TOTAL 1998 , 14,241.2 , 71,168.6 , -56,927.4 , January 1997 , 938.4 , 4,667.6 , -3,729.2 , February 1997 , 913.3 , 4,262.4 , -3,349.1 , March 1997 , 1,021.6 , 3,628.6 , -2,607.0 , April 1997 , 964.7 , 4,445.0 , -3,480.3 , May 1997 , 1,056.8 , 4,795.1 , -3,738.3 , June 1997 , 920.3 , 5,213.5 , -4,293.2 , July 1997 , 1,097.1 , 5,777.2 , -4,680.1 , August 1997 , 938.0 , 6,073.6 , -5,135.6 , September 1997 , 1,039.8 , 6,561.4 , -5,521.6 , October 1997 , 1,438.8 , 6,606.5 , -5,167.7 , November 1997 , 1,300.7 , 5,425.7 , -4,125.0 , December 1997 , 1,232.7 , 5,101.1 , -3,868.4 , TOTAL 1997 , 12,862.2 , 62,557.7 , -49,695.5 , January 1996 , 929.2 , 3,657.7 , -2,728.5 , February 1996 , 1,146.9 , 3,539.6 , -2,392.7 , March 1996 , 1,092.5 , 2,863.7 , -1,771.2 , April 1996 , 841.3 , 3,247.9 , -2,406.6 , May 1996 , 881.6 , 3,954.3 , -3,072.7 , June 1996 , 771.6 , 4,111.2 , -3,339.6 , July 1996 , 998.2 , 4,816.7 , -3,818.5 , August 1996 , 778.3 , 5,495.7 , -4,717.4 , September 1996 , 753.4 , 5,480.7 , -4,727.3 , October 1996 , 927.5 , 5,812.9 , -4,885.4 , November 1996 , 1,586.4 , 4,585.4 , -2,999.0 , December 1996 , 1,285.7 , 3,947.0 , -2,661.3 , TOTAL 1996 , 11,992.6 , 51,512.8 , -39,520.2 , January 1995 , 744.9 , 3,450.6 , -2,705.7 , February 1995 , 1,085.5 , 3,001.5 , -1,916.0 , March 1995 , 1,070.1 , 2,910.4 , -1,840.3 , April 1995 , 896.4 , 3,148.3 , -2,251.9 , May 1995 , 831.0 , 3,654.9 , -2,823.9 , June 1995 , 946.7 , 3,960.7 , -3,014.0 , July 1995 , 985.7 , 4,311.8 , -3,326.1 , August 1995 , 881.4 , 4,804.7 , -3,923.3 , September 1995 , 959.6 , 4,584.1 , -3,624.5 , October 1995 , 1,097.4 , 4,714.3 , -3,616.9 , November 1995 , 1,124.7 , 3,868.0 , -2,743.3 , December 1995 , 1,130.3 , 3,133.9 , -2,003.6 , TOTAL 1995 , 11,753.7 , 45,543.2 , -33,789.5 , January 1994 , 551.0 , 2,763.1 , -2,212.1 , February 1994 , 877.9 , 2,499.2 , -1,621.3 , March 1994 , 783.7 , 2,183.0 , -1,399.3 , April 1994 , 712.7 , 2,491.6 , -1,778.9 , May 1994 , 757.3 , 2,979.0 , -2,221.7 , June 1994 , 1,009.4 , 3,463.3 , -2,453.9 , July 1994 , 970.4 , 3,645.4 , -2,675.0 , August 1994 , 926.4 , 4,165.8 , -3,239.4 , September 1994 , 628.5 , 4,134.4 , -3,505.9 , October 1994 , 618.4 , 4,101.2 , -3,482.8 , November 1994 , 648.0 , 3,534.3 , -2,886.3 , December 1994 , 798.0 , 2,826.5 , -2,028.5 , TOTAL 1994 , 9,281.7 , 38,786.8 , -29,505.1 , January 1993 , 620.7 , 2,187.6 , -1,566.9 , February 1993 , 683.8 , 1,862.4 , -1,178.6 , March 1993 , 621.6 , 2,083.2 , -1,461.6 , April 1993 , 728.4 , 2,226.3 , -1,497.9 , May 1993 , 586.2 , 2,376.3 , -1,790.1 , June 1993 , 754.8 , 2,754.2 , -1,999.4 , July 1993 , 711.6 , 2,981.1 , -2,269.5 , August 1993 , 766.5 , 3,223.3 , -2,456.8 , September 1993 , 836.2 , 3,338.7 , -2,502.5 , October 1993 , 623.8 , 3,277.6 , -2,653.8 , November 1993 , 781.8 , 2,899.6 , -2,117.8 , December 1993 , 1,047.5 , 2,329.6 , -1,282.1 , TOTAL 1993 , 8,762.9 , 31,539.9 , -22,777.0 , January 1992 , 502.5 , 1,912.6 , -1,410.1 , February 1992 , 471.1 , 1,693.7 , -1,222.6 , March 1992 , 646.3 , 1,441.8 , -795.5 , April 1992 , 580.7 , 1,677.6 , -1,096.9 , May 1992 , 621.7 , 1,853.9 , -1,232.2 , June 1992 , 689.2 , 2,179.2 , -1,490.0 , July 1992 , 438.8 , 2,503.8 , -2,065.0 , August 1992 , 730.4 , 2,613.0 , -1,882.6 , September 1992 , 489.3 , 2,760.5 , -2,271.2 , October 1992 , 746.3 , 2,748.4 , -2,002.1 , November 1992 , 620.5 , 2,316.0 , -1,695.5 , December 1992 , 881.7 , 2,027.0 , -1,145.3 , TOTAL 1992 , 7,418.5 , 25,727.5 , -18,309.0 , January 1991 , 406.0 , 1,321.6 , -915.6 , February 1991 , 487.6 , 1,253.7 , -766.1 , March 1991 , 472.3 , 974.3 , -502.0 , April 1991 , 440.3 , 1,104.2 , -663.9 , May 1991 , 625.3 , 1,380.8 , -755.5 , June 1991 , 530.2 , 1,525.5 , -995.3 , July 1991 , 522.8 , 1,813.2 , -1,290.4 , August 1991 , 565.2 , 1,872.4 , -1,307.2 , September 1991 , 501.9 , 1,936.3 , -1,434.4 , October 1991 , 552.3 , 2,236.4 , -1,684.1 , November 1991 , 595.3 , 1,957.6 , -1,362.3 , December 1991 , 579.0 , 1,593.2 , -1,014.2 , TOTAL 1991 , 6,278.2 , 18,969.2 , -12,691.0 , January 1990 , 361.2 , 1,186.1 , -824.9 , February 1990 , 519.6 , 993.8 , -474.2 , March 1990 , 376.1 , 931.0 , -554.9 , April 1990 , 343.6 , 996.4 , -652.8 , May 1990 , 379.9 , 1,173.5 , -793.6 , June 1990 , 504.5 , 1,317.2 , -812.7 , July 1990 , 394.4 , 1,492.5 , -1,098.1 , August 1990 , 408.4 , 1,568.6 , -1,160.2 , September 1990 , 358.6 , 1,432.1 , -1,073.5 , October 1990 , 459.0 , 1,652.1 , -1,193.1 , November 1990 , 327.9 , 1,367.9 , -1,040.0 , December 1990 , 373.2 , 1,126.2 , -753.0 , TOTAL 1990 , 4,806.4 , 15,237.4 , -10,431.0 , January 1989 , 439.0 , 788.9 , -349.9 , February 1989 , 464.7 , 798.1 , -333.4 , March 1989 , 565.4 , 667.3 , -101.9 , April 1989 , 415.3 , 728.5 , -313.2 , May 1989 , 482.4 , 937.9 , -455.5 , June 1989 , 362.7 , 1,021.7 , -659.0 , July 1989 , 637.7 , 1,162.7 , -525.0 , August 1989 , 688.5 , 1,279.6 , -591.1 , September 1989 , 427.9 , 1,179.3 , -751.4 , October 1989 , 542.4 , 1,340.4 , -798.0 , November 1989 , 305.0 , 1,133.8 , -828.8 , December 1989 , 424.4 , 951.5 , -527.1 , TOTAL 1989 , 5,755.4 , 11,989.7 , -6,234.3 , January 1988 , 289.5 , 652.8 , -363.3 , February 1988 , 360.3 , 650.6 , -290.3 , March 1988 , 407.8 , 509.9 , -102.1 , April 1988 , 446.5 , 551.9 , -105.4 , May 1988 , 313.8 , 615.1 , -301.3 , June 1988 , 503.2 , 720.8 , -217.6 , July 1988 , 483.6 , 761.6 , -278.0 , August 1988 , 424.4 , 803.9 , -379.5 , September 1988 , 396.4 , 793.3 , -396.9 , October 1988 , 412.9 , 834.0 , -421.1 , November 1988 , 449.3 , 798.8 , -349.5 , December 1988 , 533.9 , 818.2 , -284.3 , TOTAL 1988 , 5,021.6 , 8,510.9 , -3,489.3 , January 1987 , 213.3 , 520.6 , -307.3 , February 1987 , 212.7 , 565.3 , -352.6 , March 1987 , 207.6 , 482.5 , -274.9 , April 1987 , 439.6 , 468.3 , -28.7 , May 1987 , 228.7 , 514.7 , -286.0 , June 1987 , 261.8 , 536.3 , -274.5 , July 1987 , 227.4 , 560.0 , -332.6 , August 1987 , 278.2 , 598.1 , -319.9 , September 1987 , 304.1 , 549.6 , -245.5 , October 1987 , 376.9 , 567.9 , -191.0 , November 1987 , 350.5 , 489.8 , -139.3 , December 1987 , 396.5 , 440.5 , -44.0 , TOTAL 1987 , 3,497.3 , 6,293.6 , -2,796.3 , January 1986 , 300.0 , 459.5 , -159.5 , February 1986 , 330.6 , 376.6 , -46.0 , March 1986 , 289.6 , 401.8 , -112.2 , April 1986 , 318.9 , 264.9 , 54.0 , May 1986 , 256.8 , 319.0 , -62.2 , June 1986 , 275.3 , 375.7 , -100.4 , July 1986 , 198.6 , 450.2 , -251.6 , August 1986 , 235.6 , 434.7 , -199.1 , September 1986 , 216.4 , 413.4 , -197.0 , October 1986 , 198.8 , 398.5 , -199.7 , November 1986 , 226.7 , 486.0 , -259.3 , December 1986 , 259.0 , 390.7 , -131.7 , TOTAL 1986 , 3,106.3 , 4,771.0 , -1,664.7 , January 1985 , 319.2 , 293.1 , 26.1 , February 1985 , 222.7 , 281.0 , -58.3 , March 1985 , 239.5 , 293.0 , -53.5 , April 1985 , 265.6 , 283.3 , -17.7 , May 1985 , 329.3 , 295.1 , 34.2 , June 1985 , 280.9 , 348.7 , -67.8 , July 1985 , 383.1 , 344.4 , 38.7 , August 1985 , 320.9 , 311.8 , 9.1 , September 1985 , 339.1 , 391.8 , -52.7 , October 1985 , 377.1 , 385.5

In [6]:
import csv

txt_file = r"mytxt.txt"
csv_file = r"mycsv.csv"

In [7]:
in_txt = csv.reader(open(txt_file, "rb"), delimiter = '\t')
out_csv = csv.writer(open(csv_file, 'wb'))

out_csv.writerows(in_txt)

FileNotFoundError: [Errno 2] No such file or directory: 'mytxt.txt'

In [ ]:
website_url1=requests.get('https://ticdata.treasury.gov/Publish/mfhhis01.txt').text

In [ ]:
from bs4 import BeautifulSoup
soup2 = BeautifulSoup(website_url1,'html')
print(soup2)

In [ ]:
My_table1 = soup2.findAll('China, Mainland')
#str_cells = str(My_table)
##cleantext = BeautifulSoup(str_cells, "lxml").get_text()
print(My_table1)

In [ ]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile

In [ ]:
df=pd.read_csv("TESTING_PHASE1.csv",sep=',')

In [ ]:
df.head()

In [ ]:
df.dropna()

In [ ]:
exrate=exrate.dropna()

In [ ]:
import statsmodels

In [ ]:
from statsmodels.tsa.arima_model import ARIMA

In [ ]:
def StartARIMAForecasting(Actual, P, D, Q):
	model = ARIMA(Actual, order=(P, D, Q))
	model_fit = model.fit(disp=0)
	prediction = model_fit.forecast()[0]
	return prediction
    
#Get exchange rates
ActualData = exrate
#Size of exchange rates
NumberOfElements = len(ActualData)
NumberOfElements

In [ ]:
#Use 70% of data as training, rest 30% to Test model
TrainingSize = int(NumberOfElements * 0.7)
TrainingData = ActualData[0:TrainingSize]
TestData = ActualData[TrainingSize:NumberOfElements]

In [ ]:
#new arrays to store actual and predictions
Actual = [x for x in TrainingData]
Predictions = list()
Actual

#in a for loop, predict values using ARIMA model
len(TestData)
for i in range(len(TestData)):
    ActualValue=TestData['Exchange Rate'].iloc[0]
    #forcast value  
    Prediction=StartARIMAForecasting(ActualData, 2,1,0)
    print('Actual=%f, Predicted=%f' % (ActualValue, Prediction))

In [ ]:
def StartARIMAForecasting(Actual, P, D, Q):
	model = ARIMA(Actual, order=(P, D, Q))
	model_fit = model.fit(disp=0)
	prediction = model_fit.forecast()[0]
	return prediction


#new arrays to store actual and predictions
Actual = [x for x in TrainingData]
Predictions = list()
Prediction=list()

#in a for loop, predict values using ARIMA model
for timepoint in range(len(TestData)):
	ActualValue =  TestData['Exchange Rate'].iloc[timepoint]
	#forcast value
	Prediction = StartARIMAForecasting(ActualData, 3,1,0)    
	print('Actual=%f, Predicted=%f' % (ActualValue, Prediction))

In [ ]:
from pandas import read_csv
from pandas import datetime
from pandas import DataFrame
from statsmodels.tsa.arima_model import ARIMA
from matplotlib import pyplot

In [ ]:
series = read_csv('TESTING_PHASE2.csv', header=0, parse_dates=[0], index_col=0, squeeze=True)
series

In [ ]:
# fit model
model = ARIMA(series, order=(5,1,0))
model_fit = model.fit(disp=0)
print(model_fit.summary())
# plot residual errors
residuals = DataFrame(model_fit.resid)
residuals.plot()
pyplot.show()
residuals.plot(kind='kde')
pyplot.show()
print(residuals.describe())

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lr=LinearRegression()

In [9]:
import pandas as pd

In [10]:

df20=pd.read_csv("RATES.csv",sep=',')

In [11]:
df20.head()

,,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,2018,1123.5,1121.4,1138.9,1151.4,1165.1,1171.0,1191.2,1183.1,1181.9,1187.7,1176.7,1168.2
1,2017,1184.9,1176.6,1189.2,1182.3,1201.7,1166.9,1146.5,1102.2,1092.2,1088.1,1059.7,1051.1
2,2016,1058.4,1049.3,1115.7,1157.0,1185.1,1218.8,1240.8,1244.0,1242.8,1244.6,1252.3,1238.0
3,2015,1246.1,1264.5,1254.8,1258.0,1270.5,1268.8,1271.2,1270.3,1263.4,1261.0,1223.7,1239.1
4,2014,1244.3,1250.4,1252.7,1266.3,1269.7,1264.9,1268.4,1270.9,1263.2,1272.1,1272.9,1275.6

In [12]:
df1_transposed = df20.T

In [ ]:
df1_transposed

In [13]:

df1_transposed.to_csv("out.csv",encoding='utf-8', index=False)

In [14]:
import pandas as pd

In [15]:
DFA=pd.read_csv("T1.csv",sep=',')

In [16]:
DFB=pd.read_csv("T2.csv",sep=',')

In [17]:
DFC=pd.read_csv("T3.csv",sep=',')

In [18]:
DFD=pd.read_csv("T4.csv",sep=',')

In [19]:
DFE=pd.read_csv("T5.csv",sep=',')

In [20]:
DFF=pd.read_csv("T6.csv",sep=',')

In [21]:
DFG=pd.read_csv("T7.csv",sep='\t')

In [22]:
DFH=pd.read_csv("T8.csv",sep='\t')

In [23]:
DFG

           Date  US(10)BOND Change %
0     30-May-19       2.217   -1.99%
1     29-May-19       2.262   -0.26%
2     28-May-19       2.268   -1.81%
3     27-May-19       2.310   -0.62%
4     24-May-19       2.324    0.09%
5     23-May-19       2.322   -2.44%
6     22-May-19       2.380   -1.98%
7     21-May-19       2.428    0.37%
8     20-May-19       2.419    0.73%
9     19-May-19       2.401    0.36%
10    17-May-19       2.393   -0.04%
11    16-May-19       2.394    0.72%
12    15-May-19       2.377   -1.53%
13    14-May-19       2.414    0.46%
14    13-May-19       2.403   -1.32%
15    12-May-19       2.435   -1.53%
16    10-May-19       2.473    0.82%
17     9-May-19       2.453   -1.29%
18     8-May-19       2.485    1.51%
19     7-May-19       2.448   -2.08%
20     6-May-19       2.500   -1.21%
21     5-May-19       2.530    0.00%
22     3-May-19       2.530   -0.59%
23     2-May-19       2.545    1.72%
24     1-May-19       2.502   -0.08%
25    30-Apr-19       2.504   -0.91%
26    29-Apr-19       2.527    1.08%
27    26-Apr-19       2.500   -1.34%
28    25-Apr-19       2.534    0.64%
29    24-Apr-19       2.518   -1.99%
...         ...         ...      ...
3977  14-Feb-05       4.077   -0.37%
3978  11-Feb-05       4.092    0.02%
3979  10-Feb-05       4.091    2.63%
3980   9-Feb-05       3.986   -0.92%
3981   8-Feb-05       4.023   -0.81%
3982   7-Feb-05       4.056   -0.66%
3983   4-Feb-05       4.083   -2.06%
3984   3-Feb-05       4.169    0.58%
3985   2-Feb-05       4.145    0.02%
3986   1-Feb-05       4.144    0.29%
3987  31-Jan-05       4.132   -0.34%
3988  28-Jan-05       4.146   -1.94%
3989  27-Jan-05       4.228    0.67%
3990  26-Jan-05       4.200    0.00%
3991  25-Jan-05       4.200    1.84%
3992  24-Jan-05       4.124   -0.48%
3993  21-Jan-05       4.144   -0.65%
3994  20-Jan-05       4.171   -0.10%
3995  19-Jan-05       4.175   -0.43%
3996  18-Jan-05       4.193   -0.64%
3997  14-Jan-05       4.220    1.27%
3998  13-Jan-05       4.167   -1.68%
3999  12-Jan-05       4.238   -0.14%
4000  11-Jan-05       4.244   -0.68%
4001  10-Jan-05       4.273   -0.05%
4002   7-Jan-05       4.275    0.28%
4003   6-Jan-05       4.263   -0.56%
4004   5-Jan-05       4.287   -0.19%
4005   4-Jan-05       4.295    1.87%
4006   3-Jan-05       4.216   -0.14%

[4007 rows x 3 columns]

In [24]:
import pandas as pd

dfL=pd.merge(DFH,DFG, on='Date')

In [25]:
print(dfL)

           Date  FED RATE  US(10)BOND Change %
0     30-May-19      2.39       2.217   -1.99%
1     29-May-19      2.39       2.262   -0.26%
2     28-May-19      2.39       2.268   -1.81%
3     24-May-19      2.38       2.324    0.09%
4     23-May-19      2.38       2.322   -2.44%
5     22-May-19      2.38       2.380   -1.98%
6     21-May-19      2.39       2.428    0.37%
7     20-May-19      2.39       2.419    0.73%
8     17-May-19      2.39       2.393   -0.04%
9     16-May-19      2.39       2.394    0.72%
10    15-May-19      2.40       2.377   -1.53%
11    14-May-19      2.38       2.414    0.46%
12    13-May-19      2.38       2.403   -1.32%
13    10-May-19      2.38       2.473    0.82%
14     9-May-19      2.38       2.453   -1.29%
15     8-May-19      2.39       2.485    1.51%
16     7-May-19      2.40       2.448   -2.08%
17     6-May-19      2.40       2.500   -1.21%
18     3-May-19      2.40       2.530   -0.59%
19     2-May-19      2.41       2.545    1.72%
20     1-May-19      2.45       2.502   -0.08%
21    30-Apr-19      2.45       2.504   -0.91%
22    29-Apr-19      2.45       2.527    1.08%
23    26-Apr-19      2.44       2.500   -1.34%
24    25-Apr-19      2.44       2.534    0.64%
25    24-Apr-19      2.44       2.518   -1.99%
26    23-Apr-19      2.44       2.569   -0.70%
27    22-Apr-19      2.44       2.587    1.07%
28    18-Apr-19      2.43       2.560   -1.31%
29    17-Apr-19      2.42       2.594    0.08%
...         ...       ...         ...      ...
3918  14-Feb-05      2.51       4.077   -0.37%
3919  11-Feb-05      2.50       4.092    0.02%
3920  10-Feb-05      2.51       4.091    2.63%
3921   9-Feb-05      2.50       3.986   -0.92%
3922   8-Feb-05      2.48       4.023   -0.81%
3923   7-Feb-05      2.50       4.056   -0.66%
3924   4-Feb-05      2.51       4.083   -2.06%
3925   3-Feb-05      2.49       4.169    0.58%
3926   2-Feb-05      2.29       4.145    0.02%
3927   1-Feb-05      2.40       4.144    0.29%
3928  31-Jan-05      2.50       4.132   -0.34%
3929  28-Jan-05      2.48       4.146   -1.94%
3930  27-Jan-05      2.39       4.228    0.67%
3931  26-Jan-05      2.33       4.200    0.00%
3932  25-Jan-05      2.29       4.200    1.84%
3933  24-Jan-05      2.26       4.124   -0.48%
3934  21-Jan-05      2.26       4.144   -0.65%
3935  20-Jan-05      2.25       4.171   -0.10%
3936  19-Jan-05      2.19       4.175   -0.43%
3937  18-Jan-05      2.31       4.193   -0.64%
3938  14-Jan-05      2.29       4.220    1.27%
3939  13-Jan-05      2.29       4.167   -1.68%
3940  12-Jan-05      2.25       4.238   -0.14%
3941  11-Jan-05      2.24       4.244   -0.68%
3942  10-Jan-05      2.26       4.273   -0.05%
3943   7-Jan-05      2.24       4.275    0.28%
3944   6-Jan-05      2.25       4.263   -0.56%
3945   5-Jan-05      2.25       4.287   -0.19%
3946   4-Jan-05      2.25       4.295    1.87%
3947   3-Jan-05      2.31       4.216   -0.14%

[3948 rows x 4 columns]

In [26]:
dfL=pd.merge(dfL,DFB, on='Date')

In [27]:
dfL=pd.merge(dfL,DFF, on='Date')

In [28]:
dfL=pd.merge(dfL,DFF, on='Date')

In [29]:
dfL=pd.merge(dfL,DFA, on='Date')

In [30]:
dfL=pd.merge(dfL,DFC, on='Date')

In [31]:
dfL=pd.merge(dfL,DFE, on='Date')

In [32]:
dfL=pd.merge(dfL,DFD, on='Date')

In [33]:
dfL.head()

,Date,FED RATE,US(10)BOND,Change %_x,Exchange Rate,Change %_y,CH(10)BOND_x,Change %_x,CH(10)BOND_y,Change %_y,CH(1)BOND,Change %_x,S&P Stock,CH(1) BOND,Shanghai Stock,Change %_y
0,30-May-19,2.39,2.217,-1.99%,6.9019,-0.18%,3.323,-0.15%,3.323,-0.15%,2.619,0.19%,2788.86,2.29,"2,905.81",-0.31%
1,29-May-19,2.39,2.262,-0.26%,6.9145,0.06%,3.328,-0.89%,3.328,-0.89%,2.614,-0.31%,2783.02,2.30,"2,914.70",0.16%
2,28-May-19,2.39,2.268,-1.81%,6.9101,0.18%,3.358,0.24%,3.358,0.24%,2.622,1.39%,2802.39,2.31,"2,909.91",0.61%
3,24-May-19,2.38,2.324,0.09%,6.9002,-0.15%,3.333,-0.18%,3.333,-0.18%,2.613,0.50%,2826.06,2.33,"2,852.99",0.02%
4,23-May-19,2.38,2.322,-2.44%,6.9105,0.06%,3.339,0.66%,3.339,0.66%,2.600,-0.57%,2822.24,2.32,"2,852.52",-1.35%

In [ ]:
dfL

In [ ]:
export_csv = dfL.to_csv (r'cleandata.csv', index = None, header=True)